version: "3.9"

# ---------- shared ENV anchor ----------
x-common-env: &env
  DB_HOST: ${DB_HOST:-mysql}
  DB_PORT: ${MYSQL_PORT:-3306}
  DB_NAME: ${MYSQL_DATABASE:-polyleave}
  DB_USER: ${MYSQL_USER:-app}
  DB_PASS: ${MYSQL_PASSWORD:-secret}

  REDIS_CLIENT: phpredis
  REDIS_HOST: redis
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

  JWT_SECRET: ${JWT_SECRET}
  GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
  GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

  MAIL_MAILER: smtp
  MAIL_HOST: ${MAIL_HOST}
  MAIL_PORT: ${MAIL_PORT}
  MAIL_USERNAME:
  MAIL_PASSWORD:
  MAIL_ENCRYPTION:

services:
  # ---------- infra ----------
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE:     ${MYSQL_DATABASE:-polyleave}
      MYSQL_USER:         ${MYSQL_USER:-app}
      MYSQL_PASSWORD:     ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpwd}
    ports:
      - "${MYSQL_PORT:-3306}:3306"

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

  migrate:
    image: amacneil/dbmate:latest
    depends_on: [mysql]
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-secret}@${DB_HOST:-mysql}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-shared}?parseTime=true}
    volumes:
      - ./migrations:/db/migrations
    command: ["--wait", "up"]

  # ---------- back-ends ----------
  laravel:
    build: ./laravel
    depends_on: [mysql, redis, migrate]
    environment: *env
    expose: ["8000"]

#  fastapi:
#    build: ./fastapi
#    depends_on: [mysql, redis, migrate]
#    environment:
#      <<: *env
#      DATABASE_URL: ${DATABASE_URL_FASTAPI:-mysql+mysqldb://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-secret}@${DB_HOST:-mysql}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-shared}}
#    expose: ["8000"]
#
#  rails:
#    build: ./rails
#    depends_on: [mysql, redis, migrate]
#    environment:
#      <<: *env
#      RAILS_ENV: ${RAILS_ENV:-production}
#    expose: ["8000"]

  # ---------- Vue front-end ----------
  frontend:
    build:
      context: ./vuejs
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    expose: ["5173:80"]

  # ---------- Nginx load balancer ----------
  lb:
    image: nginx:1.27-alpine
#    depends_on: [frontend, laravel, fastapi, rails]
    depends_on: [frontend, laravel]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
